sudo: true
language: cpp
os:
  - linux
  - osx
env:
  matrix:
    - TRAVIS_NODE_VERSION="6"
    - TRAVIS_NODE_VERSION="7"
    - TRAVIS_NODE_VERSION="8.7.0"
    - TRAVIS_NODE_VERSION="8.7.0" ENABLE_ZUUL=true

before_install:
  - nvm install $TRAVIS_NODE_VERSION
  - npm install -g node-gyp
install:
  - npm install
script:
  - npm test
