ui: tape
capabilities:
  record-video: false
  record-screenshots: false
browsers:
  - name: android
    version: [4.4,5.0]
    platform: Linux
  - name: firefox
    version: [37,38]
    platform: Windows 2012 R2
  - name: chrome
    version: [42,43]
    platform: Windows 2012 R2
  - name: ie
    version: 9..11
    platform: Windows 2008
  - name: MicrosoftEdge
    platform: Windows 10
    version: latest
  - name: safari
    version: 7..latest
  - name: ipad
    version: [7.1,8.1,9.2]
  - name: opera
    version: latest
    platform: Windows 2003
scripts:
  - "https://code.jquery.com/jquery-3.0.0.js",
  - "https://rawgit.com/alligator-io/icebreaker/master/dist/icebreaker.min.js"
server: ./test/browser/listen.js
browserify:
  - exclude: icebreaker
  - ignore: ws
  - ignore: os
  - ignore: net
  - ignore: dns
