ui: tape
capabilities:
  recordLogs: true
browsers:
  - name: firefox
    version: [37,38]
    platform: Windows 2012 R2
  - name: chrome
    version: [42,43]
    platform: Windows 2012 R2
  - name: ie
    version: 9..11
    platform: Windows 2008
  - name: MicrosoftEdge
    platform: Windows 10
    version: latest
scripts:
  - "https://code.jquery.com/jquery-3.0.0.js",
  - "https://rawgit.com/alligator-io/icebreaker/master/dist/icebreaker.min.js"
server: ./test/browser/listen.js
browserify:
  - exclude: icebreaker
  - ignore: ws
  - ignore: os
  - ignore: net
  - ignore: dns
